<?Php
$versionString='4.48.0';
# HMAC secret
#
# The HMAC secret is generated by the Android app be feeding the 
# signature SHA hash into a native (C++) library.
# This library changes presumably with every release of the app.
# Here is a tool and instructions on how to extract the key:
# https://bitbucket.org/cfib90/ojoc-keyhack
$secret='secret';
$userAgentString='Jodel/'.$versionString.' Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 5 Build/MMB29V)';